SELECT  /*+PARALLEL(18)*/ P1.DMAGENCY, P2.PMEDATE,P1.U6CYCDUE, P1.U6ORG, 
CASE WHEN DMAGENCY LIKE 'DA%' THEN 'DA'
WHEN DMAGENCY LIKE 'DQ%' THEN 'DQ'
WHEN DMAGENCY LIKE 'DKN%'  OR DMAGENCY LIKE 'SKN%' THEN 'ESP'
WHEN DMAGENCY LIKE 'DK%'  THEN 'DK'
WHEN DMAGENCY LIKE 'MA%' THEN 'MA'
WHEN DMAGENCY LIKE 'MK%' THEN 'MK'
WHEN DMAGENCY LIKE 'SA%' THEN 'SA'
WHEN DMAGENCY LIKE 'SK%' THEN 'SK'
END , count(P2.PMACCT),sum(P2.IMPORTE)
from
(
select DMACCT, DMQUE, DMAGENCY, U6CYCDUE, U6BLOCKCODE1, U6ORG
from 
(SELECT * FROM RCVRY.DELQUDA_BEGIN
where trunc(BEGINDT) = trunc(to_date('01/07/2025','dd/mm/yyyy'))
and (DMAGENCY LIKE 'DA%' OR DMAGENCY LIKE 'DK%' OR DMAGENCY LIKE 'DQ%'  OR DMAGENCY LIKE 'DK%'  OR DMAGENCY LIKE 'SK%' OR DMAGENCY LIKE 'MA%' 
OR DMAGENCY LIKE 'MK%' OR DMAGENCY LIKE 'SA%' OR DMAGENCY LIKE 'SK%')
UNION ALL 

SELECT * FROM RCVRY.DELQUDA_BEGIN_MP
where trunc(BEGINDT) = trunc(to_date('01/07/2025','dd/mm/yyyy'))
and (DMAGENCY LIKE 'DA%' OR DMAGENCY LIKE 'DK%' OR DMAGENCY LIKE 'DQ%'  OR DMAGENCY LIKE 'DK%'  OR DMAGENCY LIKE 'SK%' OR DMAGENCY LIKE 'MA%' 
OR DMAGENCY LIKE 'MK%' OR DMAGENCY LIKE 'SA%' OR DMAGENCY LIKE 'SK%')
) 
where DMACCT in (
select distinct PMACCT
from RCVRY.PMTFIL
where (trunc(PMEDATE) BETWEEN trunc(to_date('01/07/2025','dd/mm/yyyy')) AND trunc(SYSDATE - 1)
)))P1

left outer join

(
select PMACCT, PMTDATE, PMEDATE, sum(PMTAMT) as IMPORTE, PMCOLLID,PMAGENCY
from RCVRY.PMTFIL
where (trunc(PMEDATE)BETWEEN trunc(to_date('01/07/2025','dd/mm/yyyy'))AND trunc(SYSDATE - 1))
group by PMACCT, PMTDATE, PMEDATE, PMCOLLID,PMAGENCY

)P2

on P2.PMACCT = P1.DMACCT

group by P1.DMAGENCY, P2.PMEDATE,P1.U6CYCDUE, P1.U6ORG