SELECT  /*+PARALLEL(18)*/ 
    DMAGENCY,
    U6CYCDUE,
    U6ORG,
    U6BLOCKCODE1,
    U6BLOCKCODE2,
    U6BLOCKDATE1,
    U6BLOCKDATE2,
    CASE 
        WHEN DMAGENCY LIKE 'DA%' THEN '1a.Asignacion'
        WHEN DMAGENCY LIKE 'DQ%' THEN 'Demanda'
        WHEN DMAGENCY LIKE 'DKN%' OR DMAGENCY LIKE 'SKN%' THEN 'Nacional'
        WHEN DMAGENCY LIKE 'DK%' THEN 'Castigo'
        WHEN DMAGENCY LIKE 'MA%' THEN '1a.Asignacion'
        WHEN DMAGENCY LIKE 'MK%' THEN 'Castigo'
        WHEN DMAGENCY LIKE 'SA%' THEN '1a.Asignacion'
        WHEN DMAGENCY LIKE 'SK%' THEN 'Castigo'
    END AS Asignacion,
    COUNT(DMACCT),
    SUM(DMCURBAL)
FROM (
    SELECT 
        DMACCT, DMQUE, DMAGENCY, 
        U6CYCDUE, U6ORG, 
        U6BLOCKCODE1, U6BLOCKCODE2, 
        U6BLOCKDATE1, U6BLOCKDATE2, 
        DMCURBAL
    FROM RCVRY.DELQUDA_BEGIN
    WHERE TRUNC(BEGINDT) = TRUNC(TO_DATE('01/07/2025','DD/MM/YYYY'))
      AND (
        DMAGENCY LIKE 'DA%' OR 
        DMAGENCY LIKE 'DK%' OR 
        DMAGENCY LIKE 'DQ%' OR 
        DMAGENCY LIKE 'SK%' OR 
        DMAGENCY LIKE 'MA%' OR 
        DMAGENCY LIKE 'MK%' OR 
        DMAGENCY LIKE 'SA%'
      )

    UNION ALL

    SELECT 
        DMACCT, DMQUE, DMAGENCY, 
        U5CYCDUE AS U6CYCDUE,
        U5ORG AS U6ORG,
        U5BLOCKCODE1 AS U6BLOCKCODE1,
        U5BLOCKCODE2 AS U6BLOCKCODE2,
        U5BLOCKDATE1 AS U6BLOCKDATE1,
        U5BLOCKDATE2 AS U6BLOCKDATE2,
        DMCURBAL
    FROM RCVRY.DELQUDA_BEGIN_MP
    WHERE TRUNC(BEGINDT) = TRUNC(TO_DATE('01/07/2025','DD/MM/YYYY'))
      AND (
        DMAGENCY LIKE 'DA%' OR 
        DMAGENCY LIKE 'DK%' OR 
        DMAGENCY LIKE 'DQ%' OR 
        DMAGENCY LIKE 'SK%' OR 
        DMAGENCY LIKE 'MA%' OR 
        DMAGENCY LIKE 'MK%' OR 
        DMAGENCY LIKE 'SA%'
      )
)
GROUP BY 
    DMAGENCY,
    U6CYCDUE,
    U6ORG,
    U6BLOCKCODE1,
    U6BLOCKCODE2,
    U6BLOCKDATE1,
    U6BLOCKDATE2
