select 
B1.DMACCT, 
B1.DMQUE, 
B1.DMAGENCY, 
B1.U6BLOCKCODE1, 
B1.U6BLOCKCODE2, 
B1.DMLABEL1, 
B1.U6ORG, 
B1.DMCURBAL,
B2.Corte,
B1.CD_INI, 
B2.U6CYCDUE CD_FIN,
B2.DMCURBAL, 
B3.PAGOS,
B2.Fecha_Últ_Pago
from 

(select DMACCT, DMQUE, DMAGENCY, U6BLOCKCODE1, U6BLOCKCODE2, DMLABEL1, U6ORG, DMCURBAL, U6CYCDUE as CD_INI
from RCVRY.DELQUDA_BEGIN
where trunc(BEGINDT) = TO_DATE('01-07-2025', 'DD-MM-YYYY')
and DMAGENCY IN ('DA000MAM','DA000PLA','DA000RCC','DA001PLA','DA001RCC','DQA01MSE','SA000MAM','SA001PLA')) B1

left outer join

(select DMACCT, U6CYCDUE, DMCURBAL, DMSTATUS,U6CHGOFFSTAT, U6BLOCKCODE1, U6BILLCYCLE as Corte, DMPAYDT as Fecha_Últ_Pago
from RCVRY.DELQMST, RCVRY.UDA6
where DMACCTG = '6'
and DMACCT in (
select DMACCT
from RCVRY.DELQUDA_BEGIN
where trunc(BEGINDT) = TO_DATE('01-07-2025','DD-MM-YYYY')
and DMAGENCY IN ('DA000MAM','DA000PLA','DA000RCC','DA001PLA','DA001RCC','SA000MAM','SA001PLA','DQA01MSE')
)
and DMACCTG = U6ACCTG
and DMACCT = U6ACCT) B2

on B1.DMACCT = B2.DMACCT

left outer join

(select PMACCT, PMAGENCY,sum(PMTAMT) as PAGOS
from RCVRY.PMTFIL
where PMACCTG = '6'
    and (trunc(PMEDATE) >= TO_DATE('01-07-2025','DD-MM-YYYY') and trunc(PMEDATE) <= TO_DATE('31-07-2025','DD-MM-YYYY'))
and PMACCT in (
select DMACCT
from RCVRY.DELQUDA_BEGIN
where trunc(BEGINDT) = TO_DATE('01-07-2025','DD-MM-YYYY')
and DMAGENCY IN ('DA000MAM','DA000PLA','DA000RCC','DA001PLA','DA001RCC','DQA01MSE','SA000MAM','SA001PLA')
)
group by PMACCT, PMAGENCY) B3
on B1.DMACCT = B3.PMACCT AND B1.DMAGENCY=B3.PMAGENCY